name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build-windows-x64-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 17 2022"
          cmake --build . --config Release

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          mv './build/Release/$CAPI.dll' './dist/$CAPI.dll'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-capi-win-x64
          path: dist/*

  build-windows-x86-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. -A Win32 -G "Visual Studio 17 2022"
          cmake --build . --config Release

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          mv './build/Release/$CAPI.dll' './dist/$CAPI.dll'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-capi-win32
          path: dist/*

  build-linux-x64-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Build using docker
        run: |
          cd docker
          chmod +x ./build.sh
          chmod +x ./docker-entrypoint.sh
          TARGET_BUILD_ARCH=x64 ./build.sh

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          sudo mv './docker/build/$CAPI.so' './dist/$CAPI.so'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-capi-linux-x64
          path: dist/*

  build-linux-x86-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Build using docker
        run: |
          cd docker
          chmod +x ./build.sh
          chmod +x ./docker-entrypoint.sh
          TARGET_BUILD_ARCH=x86 ./build.sh

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          sudo mv './docker/build/$CAPI.so' './dist/$CAPI.so'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-capi-linux-x86
          path: dist/*
